spring:
  profiles:
    active: dev
  application:
    name: Bimo - Restaurant Campaigns API
  jackson:
    time-zone: UTC
  session:
    timeout: 10m
  datasource:
    tomcat:
      max-age: 3600
server:
  port: 8081
  servlet:
    context-path: /api
    session:
      timeout: 10m
      cookie:
        max-age: 10m

iyzipay-api:
  api-key: ${IYZICO_APIKEY:sandbox-zSQqgypAbKCdwaWX9zqjZG5aAWA7Rmxx}
  secret-key: ${IYZICO_SECRETKEY:sandbox-HsJQ66IT5f1p3kOLCM0djaV1SVFQhhyq}
  base-url: ${IYZICO_BASEURL:https://sandbox-api.iyzipay.com}

---

spring:
  profiles: dev
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb+srv://bimo-api:boWkqRuhEB8mKxno@bimo-vmnte.gcp.mongodb.net/bimo?retryWrites=true}