spring:
  profiles:
    active: dev
  application:
    name: Bimo - Restaurant Campaigns API
  jackson:
    time-zone: UTC

server:
  port: 8081
  servlet:
    context-path: /api

---

spring:
  profiles: dev
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb+srv://bimo-api:boWkqRuhEB8mKxno@bimo-vmnte.gcp.mongodb.net/bimo?retryWrites=true}